"""
sitecustomize hook — Hermes patches (Claude Code OAuth + Antigravity provider).
===============================================================================

This file is installed into the hermes-agent venv's site-packages as
``sitecustomize.py``. It runs once at Python interpreter startup and
installs import hooks for both the Claude Code billing bypass and the
Antigravity provider registration.

DO NOT EDIT THIS FILE IN THE VENV — edit the source repo instead.
"""
# hermes-claude-auth managed — do not remove this marker
# hermes-antigravity managed — do not remove this marker

from __future__ import annotations

import os
import sys

_PATCHES_DIR = os.environ.get(
    "HERMES_PATCHES_DIR",
    os.path.expanduser("~/.hermes/patches"),
)

if os.path.isdir(_PATCHES_DIR) and _PATCHES_DIR not in sys.path:
    sys.path.insert(0, _PATCHES_DIR)


def _make_import_hook(target_module, patcher_fn, label):
    """Create a MetaPathFinder that runs patcher_fn after target_module loads."""
    try:
        from importlib.abc import MetaPathFinder
        from importlib.util import find_spec
    except ImportError:
        return

    class _Finder(MetaPathFinder):
        _patched = False

        def find_spec(self, fullname, path=None, target=None):
            if fullname != target_module or self._patched:
                return None
            if self in sys.meta_path:
                sys.meta_path.remove(self)
            try:
                spec = find_spec(fullname)
            finally:
                if self not in sys.meta_path:
                    sys.meta_path.insert(0, self)
            if spec is None or spec.loader is None:
                return None
            original_exec = getattr(spec.loader, "exec_module", None)
            if not callable(original_exec):
                return None
            finder = self

            def patched_exec(module):
                original_exec(module)
                finder._patched = True
                try:
                    result = patcher_fn(module)
                    # patcher_fn may return bool for antigravity patches
                    if isinstance(result, bool) and not result:
                        sys.stderr.write(
                            f"[{label}] patch declined "
                            f"(API incompatibility detected)\n"
                        )
                except Exception as exc:
                    import traceback
                    sys.stderr.write(
                        f"[{label}] patch failed: {type(exc).__name__}: {exc}\n"
                    )
                    traceback.print_exc(file=sys.stderr)

            spec.loader.exec_module = patched_exec
            return spec

    sys.meta_path.insert(0, _Finder())


def _load_claude_bypass():
    try:
        import anthropic_billing_bypass
    except ImportError:
        return None
    return anthropic_billing_bypass


def _claude_patcher(module):
    anthropic_billing_bypass = _load_claude_bypass()
    if anthropic_billing_bypass is None:
        return
    ok = anthropic_billing_bypass.apply_patches(module)
    if not ok:
        sys.stderr.write(
            "[hermes-claude-auth] bypass declined "
            "(API incompatibility detected)\n"
        )


def _claude_error_classifier_patcher(_module):
    """Install Claude thinking-replay error recovery as early as possible.

    ``agent.conversation_loop`` imports ``classify_api_error`` directly from
    ``agent.error_classifier``. If the classifier is imported before
    ``agent.anthropic_adapter``, the regular Claude adapter hook can be too late
    for that bound name. Patch the classifier module the moment it loads.
    """
    anthropic_billing_bypass = _load_claude_bypass()
    if anthropic_billing_bypass is None:
        return
    anthropic_billing_bypass._install_thinking_replay_classifier_patch()


def _antigravity_providers_patcher(_module):
    """Full antigravity provider patch (fires on hermes_cli.providers import)."""
    import antigravity_provider_patch
    antigravity_provider_patch.apply()


def _antigravity_commands_patcher(_module):
    """Slash command metadata injection (fires on hermes_cli.commands import)."""
    import antigravity_provider_patch
    antigravity_provider_patch._patch_commands()


def _antigravity_cli_patcher(_module):
    """/agyquota CLI dispatch injection (fires on cli import)."""
    import antigravity_provider_patch
    antigravity_provider_patch._patch_cli_agyquota()


def _antigravity_auth_early_patcher(_module):
    """Early registry injection (fires on hermes_cli.auth import).

    ``hermes_cli.auth.resolve_provider()`` validates providers against
    PROVIDER_REGISTRY during the *auth* import — which happens BEFORE
    ``hermes_cli.providers`` is ever imported on the ``hermes chat
    --provider google-antigravity`` path. Without this hook the provider
    fails with "Unknown provider 'google-antigravity'".

    Both helpers are idempotent (guarded by ``if "google-antigravity"
    not in ...``), so the full apply() on the providers hook re-running
    them later is harmless.

    Also applies ``_patch_auxiliary_client()`` here so auxiliary tasks
    (title generation, context compression, vision) that probe
    ``resolve_provider_client`` early in the gateway lifecycle — before
    ``hermes_cli.providers`` imports — find google-antigravity already
    registered, avoiding "unknown provider" races.
    """
    import antigravity_provider_patch
    antigravity_provider_patch._patch_auth_registry()
    antigravity_provider_patch._patch_providers()
    antigravity_provider_patch._patch_auxiliary_client()


def _antigravity_auth_commands_patcher(_module):
    """Patch `hermes auth add google-antigravity` when auth_commands loads first.

    The `hermes auth add ...` CLI path imports `hermes_cli.auth_commands`
    directly. If this happens before the `hermes_cli.auth` hook fires,
    google-antigravity is treated as an API-key provider and prompts for a key.
    """
    import antigravity_provider_patch
    antigravity_provider_patch._patch_auth_registry()


def _antigravity_auxiliary_patcher(_module):
    """Patch auxiliary_client even when it imports before hermes_cli.auth."""
    import antigravity_provider_patch
    antigravity_provider_patch._patch_auth_registry()
    antigravity_provider_patch._patch_providers()
    antigravity_provider_patch._patch_auxiliary_client()


def _antigravity_main_patcher(_module):
    """Model picker patches (fires on hermes_cli.main import, before cmd_model).

    This must fire BEFORE select_provider_and_model is called, so the
    TUI provider list includes google-antigravity from the first run.
    """
    import antigravity_provider_patch
    ok1 = antigravity_provider_patch._patch_models_module()
    ok2 = antigravity_provider_patch._patch_model_picker()
    if not (ok1 and ok2):
        sys.stderr.write(
            "[hermes-antigravity-main] TUI picker patches skipped "
            "(API incompatibility — will still work via hermes config)\n"
        )


def _antigravity_model_switch_patcher(_module):
    """Gateway /model picker injection (fires on hermes_cli.model_switch import).

    Must fire AFTER the module body finishes so ``list_authenticated_providers``
    is defined. The providers/main hooks run while model_switch is still
    mid-import (it does ``from hermes_cli.providers import get_label``), so the
    picker wrap is deferred to this dedicated hook to avoid a circular-import
    race. ``_patch_models_module`` is re-run first (idempotent) to guarantee the
    curated Antigravity model list exists before the row is built.
    """
    import antigravity_provider_patch
    antigravity_provider_patch._patch_models_module()
    ok = antigravity_provider_patch._patch_model_switch_picker()
    if isinstance(ok, bool) and not ok:
        sys.stderr.write(
            "[hermes-antigravity-model-switch] /model picker injection skipped "
            "(API incompatibility — provider still usable via hermes config)\n"
        )


def _antigravity_runtime_provider_patcher(_module):
    """Runtime provider injection (fires on hermes_cli.runtime_provider import).

    The full apply() runs on the hermes_cli.providers import hook, but on the
    gateway startup path hermes_cli.providers can import while
    hermes_cli.runtime_provider is still mid-import — at which point
    ``resolve_runtime_provider`` is not yet defined, so _patch_runtime_provider()
    silently skips and the gateway falls back to the default provider with no
    credentials ("No inference provider configured"). This dedicated hook fires
    AFTER runtime_provider finishes loading, guaranteeing the resolver exists.
    _patch_runtime_provider() is idempotent (guarded by
    ``rp._antigravity_runtime_patched``), so re-running it here is harmless even
    if apply() already succeeded.
    """
    import antigravity_provider_patch
    ok = antigravity_provider_patch._patch_runtime_provider()
    if isinstance(ok, bool) and not ok:
        sys.stderr.write(
            "[hermes-antigravity-runtime] runtime_provider injection skipped "
            "(API incompatibility detected)\n"
        )


def _antigravity_webui_config_patcher(_module):
    """WebUI /api/models picker injection (fires on api.config import)."""
    import antigravity_provider_patch
    ok = antigravity_provider_patch._patch_webui_config()
    if isinstance(ok, bool) and not ok:
        sys.stderr.write(
            "[hermes-antigravity-webui] WebUI model picker injection skipped "
            "(API incompatibility — provider still usable via hermes config)\n"
        )


try:
    _make_import_hook("agent.error_classifier", _claude_error_classifier_patcher, "hermes-claude-auth-errors")
    _make_import_hook("agent.anthropic_adapter", _claude_patcher, "hermes-claude-auth")
    _make_import_hook(
        "hermes_cli.auth", _antigravity_auth_early_patcher, "hermes-antigravity-auth"
    )
    _make_import_hook(
        "hermes_cli.auth_commands", _antigravity_auth_commands_patcher,
        "hermes-antigravity-auth-commands"
    )
    _make_import_hook(
        "hermes_cli.providers", _antigravity_providers_patcher, "hermes-antigravity"
    )
    _make_import_hook(
        "hermes_cli.commands", _antigravity_commands_patcher,
        "hermes-antigravity-commands"
    )
    _make_import_hook(
        "cli", _antigravity_cli_patcher, "hermes-antigravity-cli"
    )
    _make_import_hook(
        "agent.auxiliary_client", _antigravity_auxiliary_patcher, "hermes-antigravity-auxiliary"
    )
    _make_import_hook(
        "hermes_cli.runtime_provider", _antigravity_runtime_provider_patcher,
        "hermes-antigravity-runtime"
    )
    _make_import_hook(
        "hermes_cli.main", _antigravity_main_patcher, "hermes-antigravity-main"
    )
    _make_import_hook(
        "hermes_cli.model_switch", _antigravity_model_switch_patcher,
        "hermes-antigravity-model-switch"
    )
    _make_import_hook(
        "api.config", _antigravity_webui_config_patcher,
        "hermes-antigravity-webui"
    )
except Exception as _exc:
    sys.stderr.write(f"[hermes-sitecustomize] hook install failed: {_exc}\n")
