"""
sitecustomize hook — Hermes patches (Claude Code OAuth + Antigravity provider).
===============================================================================

This file is installed into the hermes-agent venv's site-packages as
``sitecustomize.py``. It runs once at Python interpreter startup and
installs import hooks for both the Claude Code billing bypass and the
Antigravity provider registration.

DO NOT EDIT THIS FILE IN THE VENV — edit the source repo instead.
"""
# hermes-claude-auth managed — do not remove this marker
# hermes-antigravity managed — do not remove this marker

from __future__ import annotations

import os
import sys

_PATCHES_DIR = os.environ.get(
    "HERMES_PATCHES_DIR",
    os.path.expanduser("~/.hermes/patches"),
)

if os.path.isdir(_PATCHES_DIR) and _PATCHES_DIR not in sys.path:
    sys.path.insert(0, _PATCHES_DIR)


def _make_import_hook(target_module, patcher_fn, label):
    """Create a MetaPathFinder that runs patcher_fn after target_module loads."""
    try:
        from importlib.abc import MetaPathFinder
        from importlib.util import find_spec
    except ImportError:
        return

    class _Finder(MetaPathFinder):
        _patched = False

        def find_spec(self, fullname, path=None, target=None):
            if fullname != target_module or self._patched:
                return None
            if self in sys.meta_path:
                sys.meta_path.remove(self)
            try:
                spec = find_spec(fullname)
            finally:
                if self not in sys.meta_path:
                    sys.meta_path.insert(0, self)
            if spec is None or spec.loader is None:
                return None
            original_exec = getattr(spec.loader, "exec_module", None)
            if not callable(original_exec):
                return None
            finder = self

            def patched_exec(module):
                original_exec(module)
                finder._patched = True
                try:
                    patcher_fn(module)
                except Exception as exc:
                    import traceback
                    sys.stderr.write(
                        f"[{label}] patch failed: {type(exc).__name__}: {exc}\n"
                    )
                    traceback.print_exc(file=sys.stderr)

            spec.loader.exec_module = patched_exec
            return spec

    sys.meta_path.insert(0, _Finder())


def _claude_patcher(module):
    import anthropic_billing_bypass
    anthropic_billing_bypass.apply_patches(module)


def _antigravity_patcher(_module):
    import antigravity_provider_patch
    antigravity_provider_patch.apply()


try:
    _make_import_hook("agent.anthropic_adapter", _claude_patcher, "hermes-claude-auth")
    _make_import_hook("hermes_cli.providers", _antigravity_patcher, "hermes-antigravity")
except Exception as _exc:
    sys.stderr.write(f"[hermes-sitecustomize] hook install failed: {_exc}\n")
